[package]
name = "artisticvampyre/meteor"
version = "0.0.3"
license = "MIT"
authors = ["ArtisticVampyre"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Signal = "red-blox/signal@2.0.2"